name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Install Node.js dependencies and Build ---
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Unified version for both frontend and backend
          cache: 'npm'

      - name: Install dependencies and build project
        run: |
          npm install -g @angular/cli # Global Angular CLI for frontend build
          npm install
          npm run build --if-present

      # --- Deployment to Azure Web App ---
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CelesContainerWebApp' # Replace with your Azure Web App name
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FBA1DA16A8A484FA3AD7D58823C53F3 }}
          package: '.'  # Deploy the entire repository
